GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "blorg",
  "author": "izzy miller",
  "url": "www.izzy.co",
  "likes": 2,
  "userId": "64bc20207bc27a66ab7ac5b9"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "ma",
  "name": "Sarah Test",
  "password": "S4r4hT3st"
}